name = "Paxultek"
uuid = "b625ba5d-8e22-4a0c-9250-c8ca070d29e6"
authors = ["Erik Edin <erikedin@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
